name = "quiet-the-mowers"
compatibility_date = "2026-04-29"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "qtm-db"
database_id = "0715ecc3-0eb0-4dbc-9b82-62c3d8290cc7"

[[kv_namespaces]]
binding = "SESSION"
id = "7b45729323d94daf9f81503ca819c08f"
